### ISSUE TITLE
Setup initial Angular app

### ISSUE THREAD

**Issue by marijadjurisic** [marijadjurisic/airvironment-frontend-fall-2021#1]

**Comment by marijadjurisic** [comment]
- [ ] Create Hello world application #2
- [ ] Setting up ngrx #3
- [ ] Setting up project configuration #4
- [ ] Add dependency libraries #5
- [ ] Create Angular interceptor for getting data from BE #6
