### ISSUE TITLE
Create All data page

### ISSUE THREAD

**Issue by marijadjurisic** [marijadjurisic/airvironment-frontend-fall-2021#11]

**Comment by marijadjurisic** [comment]
- [ ] Create All data component list #13 
- [ ] Create All data card with mock data #14
- [ ] Display data from API #15
