### ISSUE TITLE
Create Average page

### ISSUE THREAD

**Issue by marijadjurisic** [marijadjurisic/airvironment-frontend-fall-2021#12]

**Comment by marijadjurisic** [comment]
- [ ] Create Average component list #16
- [ ] Create Average card with mock data #17
- [ ] Display data from API #18
- [ ] Display colors based on value of air temperature/humidity/pollution #19
- [ ] Create Filter component #20
- [ ] Implement filters functionality #21
